In [2]:
import numpy as np

In [3]:
a=np.array([10,20,30])
a*10

array([100, 200, 300])

In [11]:
b=np.array([[10,20,30,],[40,50,60]])
c=np.array([2,3,4])
b+c,b-c,b*c,b/c

(array([[12, 23, 34],
        [42, 53, 64]]),
 array([[ 8, 17, 26],
        [38, 47, 56]]),
 array([[ 20,  60, 120],
        [ 80, 150, 240]]),
 array([[ 5.        ,  6.66666667,  7.5       ],
        [20.        , 16.66666667, 15.        ]]))

In [12]:
img=np.zeros([512,512],dtype=np.uint8)
print(img)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
img=np.zeros([512,512])+255
print(img)

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [15]:
img=np.ones([512,512])*255
print(img)

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [25]:
img=np.eye(512,dtype=np.uint8)*255
print(img)

[[255   0   0 ...   0   0   0]
 [  0 255   0 ...   0   0   0]
 [  0   0 255 ...   0   0   0]
 ...
 [  0   0   0 ... 255   0   0]
 [  0   0   0 ...   0 255   0]
 [  0   0   0 ...   0   0 255]]


In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
for i in np.arange(0,10,1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
np.linspace(0, 10, 5) #0부터 10까지 균등하게 나눠

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.logspace(0,180,11)

array([1.e+000, 1.e+018, 1.e+036, 1.e+054, 1.e+072, 1.e+090, 1.e+108,
       1.e+126, 1.e+144, 1.e+162, 1.e+180])

In [30]:
result=np.logspace(0,np.pi,11)
print(np.sin(result))

[ 0.84147098  0.88205532 -0.89468185  0.61730197 -0.71239905 -0.45947264
  0.97116725  0.88523357 -0.63128174 -0.20024967 -0.01337074]


In [31]:
a= np.array([1,3,4,])
np.insert(a,1,2) #a 에 1자리에 2를 넣어줘

array([1, 2, 3, 4])

In [34]:
b=np.array([[1,1],[2,2],[3,3]],dtype=np.uint8)
np.insert(b,1,4,axis=0) #하나면 브로드 캐스팅 [4,20]

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [35]:
b=np.array([[1,1],[2,2],[3,3]],dtype=np.uint8)
np.insert(b,1,4,axis=1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]], dtype=uint8)

In [39]:
c = np.array([[1, 2, 3], [4, 5, 6]])
np.flip(c, axis=0,1)

array([[4, 5, 6],
       [1, 2, 3]])

In [40]:
c = np.array([[1, 2, 3], [4, 5, 6]])

np.flip(c, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

In [41]:
b=np.array([[1,1],[2,2],[3,3]])
np.insert(b,1,[1,2,3],axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [42]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [0,1,2]])
a[1:,0:2]


array([[4, 5],
       [7, 8],
       [0, 1]])

In [43]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a%2 ==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [44]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [45]:
a:list = [1,2,3,4,5,6]
print(max(a))


6


In [46]:
print(min(a))

1


In [ ]:
import numpy as np

a = np.array([10, 20, 30])
a.max(), a.min()

In [47]:
a = np.array([10, 20, 30],dtype=np.int32)
sum =0
for item in a:
    sum+=item
    mean = sum/a.size
    print(mean)

3.3333333333333335
10.0
20.0


In [48]:
a.astype(np.float64)

array([10., 20., 30.])

In [52]:
b= np.array([[1,1],[2,2],[3,3]])
print(b.shape)
f_b=b.flatten()
print(b)
print(f_b)

(3, 2)
[[1 1]
 [2 2]
 [3 3]]
[1 1 2 2 3 3]


In [54]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort() # 배열의 정렬(오름차순)
print(c)
c[::-1] # 내림차순 정렬

[19 24 35 55 69 99]


array([99, 69, 55, 35, 24, 19])

In [57]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort(kind="Q") # 배열의 정렬(오름차순)
print(c)
c[::-1] # 내림차순 정렬

[19 24 35 55 69 99]


array([99, 69, 55, 35, 24, 19])

In [67]:
d = np.array([[35, 24, 55],
              [69, 19, 9],
              [4, 1, 11]])
#d.sort(axis=0)   # axis=0 방향 정렬 rows
np.flip(d,axis=0)

array([[ 4,  1, 11],
       [69, 19,  9],
       [35, 24, 55]])

In [75]:
np.flip(d,axis=1)

array([[ 9,  4,  1],
       [35, 19, 11],
       [69, 55, 24]])

In [94]:
d = np.array([[35, 24, 55],
              [69, 19, 9],
              [4, 1, 11]])
d.sort(axis=1)
print(d)
np.flip(d,axis=1)

[[24 35 55]
 [ 9 19 69]
 [ 1  4 11]]


array([[55, 35, 24],
       [69, 19,  9],
       [11,  4,  1]])

In [96]:
d = np.array([[35, 24, 55],
              [69, 19, 9],
              [4, 1, 11]])
d.sort(axis=0)
print(d)
np.flip(d,axis=0)

[[ 4  1  9]
 [35 19 11]
 [69 24 55]]


array([[69, 24, 55],
       [35, 19, 11],
       [ 4,  1,  9]])

In [88]:
a = [1, 2, 3, 4, 5, 6, 7, 8]

In [90]:
a1=np.reshape(a,[-1,2])
print(a1)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [99]:
a = np.arange(1,9)   # 1차원 배열 a
b = a.reshape(2,2,2)
print(a) # 3차원 배열 b
b

[1 2 3 4 5 6 7 8]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [102]:
a = np.arange(1,10).reshape(3,3)
b = np.full((3,3),3)
print(a)
print("-"*50)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [103]:
rnd = np.random.randn(5)*10+165 #평균값이 165, 표준편차가 10인 값 생성
rnd

array([169.98621628, 155.3968058 , 157.80116505, 146.25543469,
       172.02491638])

In [106]:
np.random.seed(1000)
nums = np.random.normal(loc=165, scale=10, size=(3, 4)).round(2)
nums


array([[156.96, 168.21, 164.75, 171.44],
       [161.99, 168.89, 163.93, 160.2 ],
       [170.95, 160.35, 171.67, 156.94]])

In [114]:




#test_data=np.arange(50).random.normal(scale=10)
#train_test_split()



[20 19 17 25 36 43 45 23 40 30 31 35 39  3 10 26 49 28 33 15 13  6 32 37
 38 50  8  4 34 18 41 11  1 14 44 47  5 29  2 16]
[24  9 42 48 27 46 21  7 12 22]


In [ ]:
def train_test_split():
    a=np.arange(1,51)
    for _ in range(50):
        np.random.shuffle(a)

    trian_data= a[:40]
    #print(trian_data)
    test_data = a[40:]
    #print(test_data)
    return (trian_data,test_data)
(X_train,X_test)= train_test_split()

In [115]:
a = np.array([[1,2],[1,-3]])
b=  np.array([6,1])
s= np.linalg.solve(a,b)
print(s)

[4. 1.]


In [120]:
a = np.array([[1,1,-1],
             [2,-1,3],
             [1,2,1]],dtype='int32')
b= np.array([0,9,8])
s= np.linalg.solve(a,b)
print(s)

[1. 2. 3.]


In [123]:
det_a=np.linalg.det(a)
print(det_a)

-11.000000000000002
